#!/usr/bin/env bash
#
# gen_checked_arithmetic.sh — emit a portable checked-arithmetic C header.
#
# Generates a header with CK_ADD/CK_SUB/CK_MUL macros that select C23
# <stdckdint.h> ckd_* when available and fall back to GCC/Clang
# __builtin_*_overflow, matching skills/c/modern-c/SKILL.md § Checked Arithmetic
# and the secure-coding integer-safety rules (each macro returns true on
# overflow). Keep in sync with those (the source of truth).
#
# USAGE
#   gen_checked_arithmetic.sh [--guard MACRO] [--output FILE]
#
# OPTIONS
#   --guard MACRO   Include-guard macro name (default CHECKED_ARITHMETIC_H).
#   --output FILE   Write to FILE instead of stdout.
#   -h, --help      Show this help and exit.
#
# EXAMPLES
#   gen_checked_arithmetic.sh > checked_arithmetic.h
#   gen_checked_arithmetic.sh --guard MYPROJ_CK_H --output src/ck.h
#
# EXIT CODES
#   0  success
#   2  usage error
#
# DEPENDENCIES
#   bash (3.2+), printf. No external tools. The emitted header needs C23
#   <stdckdint.h> or a GCC/Clang compiler (it #errors otherwise).
#
set -Eeuo pipefail

die() {
	printf 'error: %s | fix: run --help\n' "$1" >&2
	exit 2
}

show_help() {
	grep -E '^#( |$)' "$0" | sed -E 's/^# ?//'
}

GUARD="CHECKED_ARITHMETIC_H"
OUTPUT=""

while [[ $# -gt 0 ]]; do
	case "$1" in
		--guard)
			[[ $# -ge 2 ]] || die "--guard needs a value"
			GUARD="$2"
			shift 2
			;;
		--guard=*)
			GUARD="${1#*=}"
			shift
			;;
		--output)
			[[ $# -ge 2 ]] || die "--output needs a value"
			OUTPUT="$2"
			shift 2
			;;
		--output=*)
			OUTPUT="${1#*=}"
			shift
			;;
		-h | --help)
			show_help
			exit 0
			;;
		*)
			die "unknown argument \"$1\""
			;;
	esac
done

case "${GUARD}" in
	[A-Za-z_]*) ;;
	*) die "invalid --guard \"${GUARD}\" (want a C macro identifier)" ;;
esac

emit() {
	# Unquoted heredoc: only ${GUARD} interpolates (the C body has no '$').
	cat <<EOF
/* checked_arithmetic.h — overflow-checked integer arithmetic.
 *
 * CK_ADD(r, a, b) / CK_SUB / CK_MUL store the (wrapped) result in *r and
 * evaluate to true on overflow, so the caller never uses a junk value:
 *
 *     size_t total;
 *     if (CK_ADD(&total, count, hdr) || CK_MUL(&total, total, width))
 *         return ERR_OVERFLOW;
 *     void *p = malloc(total);
 *
 * Backend: C23 <stdckdint.h> if present, else GCC/Clang __builtin_*_overflow.
 * Generated by gen_checked_arithmetic.sh; keep behavior in sync with
 * skills/c/modern-c/SKILL.md.
 */
#ifndef ${GUARD}
#define ${GUARD}

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L && defined(__has_include)
#  if __has_include(<stdckdint.h>)
#    include <stdckdint.h>
#    define CK_ADD(r, a, b) ckd_add((r), (a), (b))
#    define CK_SUB(r, a, b) ckd_sub((r), (a), (b))
#    define CK_MUL(r, a, b) ckd_mul((r), (a), (b))
#    define CK_BACKEND "C23 <stdckdint.h>"
#  endif
#endif

#if !defined(CK_ADD)
#  if defined(__GNUC__) || defined(__clang__)
#    define CK_ADD(r, a, b) __builtin_add_overflow((a), (b), (r))
#    define CK_SUB(r, a, b) __builtin_sub_overflow((a), (b), (r))
#    define CK_MUL(r, a, b) __builtin_mul_overflow((a), (b), (r))
#    define CK_BACKEND "__builtin_*_overflow"
#  else
#    error "no checked-arithmetic backend: need C23 <stdckdint.h> or GCC/Clang"
#  endif
#endif

#endif /* ${GUARD} */
EOF
}

if [[ -n "${OUTPUT}" ]]; then
	emit >"${OUTPUT}"
	printf 'wrote %s\n' "${OUTPUT}" >&2
else
	emit
fi
